from .TurbineGovernorDynamics import TurbineGovernorDynamics
from .CGMESProfile import Profile


class GovSteamFV4(TurbineGovernorDynamics):
    """
    Detailed electro-hydraulic governor for steam unit.

    :cpsmn: Minimum value of pressure regulator output (Cpsmn).  Typical Value = -1. Default: 0.0
    :cpsmx: Maximum value of pressure regulator output (Cpsmx).  Typical Value = 1. Default: 0.0
    :crmn: Minimum value of regulator set-point (Crmn).  Typical Value = 0. Default: 0.0
    :crmx: Maximum value of regulator set-point (Crmx).  Typical Value = 1.2. Default: 0.0
    :kdc: Derivative gain of pressure regulator (Kdc).  Typical Value = 1. Default: 0.0
    :kf1: Frequency bias (reciprocal of droop) (Kf1).  Typical Value = 20. Default: 0.0
    :kf3: Frequency control (reciprocal of droop) (Kf3).  Typical Value = 20. Default: 0.0
    :khp: Fraction  of total turbine output generated by HP part (Khp).  Typical Value = 0.35. Default: 0.0
    :kic: Integral gain of pressure regulator (Kic).  Typical Value = 0.0033. Default: 0.0
    :kip: Integral gain of pressure feedback regulator (Kip).  Typical Value = 0.5. Default: 0.0
    :kit: Integral gain of electro-hydraulic regulator (Kit).  Typical Value = 0.04. Default: 0.0
    :kmp1: First gain coefficient of  intercept valves characteristic (Kmp1).  Typical Value = 0.5. Default: 0.0
    :kmp2: Second gain coefficient of intercept valves characteristic (Kmp2).  Typical Value = 3.5. Default: 0.0
    :kpc: Proportional gain of pressure regulator (Kpc).  Typical Value = 0.5. Default: 0.0
    :kpp: Proportional gain of pressure feedback regulator (Kpp).  Typical Value = 1. Default: 0.0
    :kpt: Proportional gain of electro-hydraulic regulator (Kpt).  Typical Value = 0.3. Default: 0.0
    :krc: Maximum variation of fuel flow (Krc).  Typical Value = 0.05. Default: 0.0
    :ksh: Pressure loss due to flow friction in the boiler tubes (Ksh).  Typical Value = 0.08. Default: 0.0
    :lpi: Maximum negative power error (Lpi).  Typical Value = -0.15. Default: 0.0
    :lps: Maximum positive power error (Lps).  Typical Value = 0.03. Default: 0.0
    :mnef: Lower limit for frequency correction (MN).  Typical Value = -0.05. Default: 0.0
    :mxef: Upper limit for frequency correction (MX).  Typical Value = 0.05. Default: 0.0
    :pr1: First value of pressure set point static characteristic (Pr1).  Typical Value = 0.2. Default: 0.0
    :pr2: Second value of pressure set point static characteristic, corresponding to Ps0 = 1.0 PU (Pr2).  Typical Value = 0.75. Default: 0.0
    :psmn: Minimum value of pressure set point static characteristic (Psmn).  Typical Value = 1. Default: 0.0
    :rsmimn: Minimum value of integral regulator (Rsmimn).  Typical Value = 0. Default: 0.0
    :rsmimx: Maximum value of integral regulator (Rsmimx).  Typical Value = 1.1. Default: 0.0
    :rvgmn: Minimum value of integral regulator (Rvgmn).  Typical Value = 0. Default: 0.0
    :rvgmx: Maximum value of integral regulator (Rvgmx).  Typical Value = 1.2. Default: 0.0
    :srmn: Minimum valve opening (Srmn).  Typical Value = 0. Default: 0.0
    :srmx: Maximum valve opening (Srmx).  Typical Value = 1.1. Default: 0.0
    :srsmp: Intercept valves characteristic discontinuity point (Srsmp).  Typical Value = 0.43. Default: 0.0
    :svmn: Maximum regulator gate closing velocity (Svmn).  Typical Value = -0.0333. Default: 0.0
    :svmx: Maximum regulator gate opening velocity (Svmx).  Typical Value = 0.0333. Default: 0.0
    :ta: Control valves rate opening time (Ta).  Typical Value = 0.8. Default: 0.0
    :tam: Intercept valves rate opening time (Tam).  Typical Value = 0.8. Default: 0.0
    :tc: Control valves rate closing time (Tc).  Typical Value = 0.5. Default: 0.0
    :tcm: Intercept valves rate closing time (Tcm).  Typical Value = 0.5. Default: 0.0
    :tdc: Derivative time constant of pressure regulator (Tdc).  Typical Value = 90. Default: 0.0
    :tf1: Time constant of fuel regulation (Tf1).  Typical Value = 10. Default: 0.0
    :tf2: Time constant of steam chest (Tf2).  Typical Value = 10. Default: 0.0
    :thp: High pressure (HP) time constant of the turbine (Thp).  Typical Value = 0.15. Default: 0.0
    :tmp: Low pressure (LP) time constant of the turbine (Tmp).  Typical Value = 0.4. Default: 0.0
    :trh: Reheater  time constant of the turbine (Trh).  Typical Value = 10. Default: 0.0
    :tv: Boiler time constant (Tv).  Typical Value = 60. Default: 0.0
    :ty: Control valves servo time constant (Ty).  Typical Value = 0.1. Default: 0.0
    :y: Coefficient of linearized equations of turbine (Stodola formulation) (Y).  Typical Value = 0.13. Default: 0.0
    :yhpmn: Minimum control valve position (Yhpmn).  Typical Value = 0. Default: 0.0
    :yhpmx: Maximum control valve position (Yhpmx).  Typical Value = 1.1. Default: 0.0
    :ympmn: Minimum intercept valve position (Ympmn).  Typical Value = 0. Default: 0.0
    :ympmx: Maximum intercept valve position (Ympmx).  Typical Value = 1.1. Default: 0.0
    """

    possibleProfileList = {
        "class": [Profile.DY.value, ],
        "cpsmn": [Profile.DY.value, ],
        "cpsmx": [Profile.DY.value, ],
        "crmn": [Profile.DY.value, ],
        "crmx": [Profile.DY.value, ],
        "kdc": [Profile.DY.value, ],
        "kf1": [Profile.DY.value, ],
        "kf3": [Profile.DY.value, ],
        "khp": [Profile.DY.value, ],
        "kic": [Profile.DY.value, ],
        "kip": [Profile.DY.value, ],
        "kit": [Profile.DY.value, ],
        "kmp1": [Profile.DY.value, ],
        "kmp2": [Profile.DY.value, ],
        "kpc": [Profile.DY.value, ],
        "kpp": [Profile.DY.value, ],
        "kpt": [Profile.DY.value, ],
        "krc": [Profile.DY.value, ],
        "ksh": [Profile.DY.value, ],
        "lpi": [Profile.DY.value, ],
        "lps": [Profile.DY.value, ],
        "mnef": [Profile.DY.value, ],
        "mxef": [Profile.DY.value, ],
        "pr1": [Profile.DY.value, ],
        "pr2": [Profile.DY.value, ],
        "psmn": [Profile.DY.value, ],
        "rsmimn": [Profile.DY.value, ],
        "rsmimx": [Profile.DY.value, ],
        "rvgmn": [Profile.DY.value, ],
        "rvgmx": [Profile.DY.value, ],
        "srmn": [Profile.DY.value, ],
        "srmx": [Profile.DY.value, ],
        "srsmp": [Profile.DY.value, ],
        "svmn": [Profile.DY.value, ],
        "svmx": [Profile.DY.value, ],
        "ta": [Profile.DY.value, ],
        "tam": [Profile.DY.value, ],
        "tc": [Profile.DY.value, ],
        "tcm": [Profile.DY.value, ],
        "tdc": [Profile.DY.value, ],
        "tf1": [Profile.DY.value, ],
        "tf2": [Profile.DY.value, ],
        "thp": [Profile.DY.value, ],
        "tmp": [Profile.DY.value, ],
        "trh": [Profile.DY.value, ],
        "tv": [Profile.DY.value, ],
        "ty": [Profile.DY.value, ],
        "y": [Profile.DY.value, ],
        "yhpmn": [Profile.DY.value, ],
        "yhpmx": [Profile.DY.value, ],
        "ympmn": [Profile.DY.value, ],
        "ympmx": [Profile.DY.value, ],
    }

    serializationProfile = {}

    __doc__ += "\nDocumentation of parent class TurbineGovernorDynamics:\n" + TurbineGovernorDynamics.__doc__

    def __init__(self, cpsmn = 0.0, cpsmx = 0.0, crmn = 0.0, crmx = 0.0, kdc = 0.0, kf1 = 0.0, kf3 = 0.0, khp = 0.0, kic = 0.0, kip = 0.0, kit = 0.0, kmp1 = 0.0, kmp2 = 0.0, kpc = 0.0, kpp = 0.0, kpt = 0.0, krc = 0.0, ksh = 0.0, lpi = 0.0, lps = 0.0, mnef = 0.0, mxef = 0.0, pr1 = 0.0, pr2 = 0.0, psmn = 0.0, rsmimn = 0.0, rsmimx = 0.0, rvgmn = 0.0, rvgmx = 0.0, srmn = 0.0, srmx = 0.0, srsmp = 0.0, svmn = 0.0, svmx = 0.0, ta = 0.0, tam = 0.0, tc = 0.0, tcm = 0.0, tdc = 0.0, tf1 = 0.0, tf2 = 0.0, thp = 0.0, tmp = 0.0, trh = 0.0, tv = 0.0, ty = 0.0, y = 0.0, yhpmn = 0.0, yhpmx = 0.0, ympmn = 0.0, ympmx = 0.0, *args, **kw_args):
        super().__init__(*args, **kw_args)

        self.cpsmn = cpsmn
        self.cpsmx = cpsmx
        self.crmn = crmn
        self.crmx = crmx
        self.kdc = kdc
        self.kf1 = kf1
        self.kf3 = kf3
        self.khp = khp
        self.kic = kic
        self.kip = kip
        self.kit = kit
        self.kmp1 = kmp1
        self.kmp2 = kmp2
        self.kpc = kpc
        self.kpp = kpp
        self.kpt = kpt
        self.krc = krc
        self.ksh = ksh
        self.lpi = lpi
        self.lps = lps
        self.mnef = mnef
        self.mxef = mxef
        self.pr1 = pr1
        self.pr2 = pr2
        self.psmn = psmn
        self.rsmimn = rsmimn
        self.rsmimx = rsmimx
        self.rvgmn = rvgmn
        self.rvgmx = rvgmx
        self.srmn = srmn
        self.srmx = srmx
        self.srsmp = srsmp
        self.svmn = svmn
        self.svmx = svmx
        self.ta = ta
        self.tam = tam
        self.tc = tc
        self.tcm = tcm
        self.tdc = tdc
        self.tf1 = tf1
        self.tf2 = tf2
        self.thp = thp
        self.tmp = tmp
        self.trh = trh
        self.tv = tv
        self.ty = ty
        self.y = y
        self.yhpmn = yhpmn
        self.yhpmx = yhpmx
        self.ympmn = ympmn
        self.ympmx = ympmx

    def __str__(self):
        str = "class=GovSteamFV4\n"
        attributes = self.__dict__
        for key in attributes.keys():
            str = str + key + "={}\n".format(attributes[key])
        return str
