from .TurbineGovernorDynamics import TurbineGovernorDynamics


class GovSteamEU(TurbineGovernorDynamics):
    """
    Simplified boiler and steam turbine with PID governor.

    :mwbase: Base for power values (<i>MWbase</i>) (&gt; 0).  Unit = MW. Default: 0.0
    :tp: Power transducer time constant (<i>Tp</i>) (&gt;= 0).  Typical value = 0,07. Default: 0
    :ke: Gain of the power controller (<i>Ke</i>).  Typical value = 0,65. Default: 0.0
    :tip: Integral time constant of the power controller (<i>Tip</i>) (&gt;= 0).  Typical value = 2. Default: 0
    :tdp: Derivative time constant of the power controller (<i>Tdp</i>) (&gt;= 0).  Typical value = 0. Default: 0
    :tfp: Time constant of the power controller (<i>Tfp</i>) (&gt;= 0).  Typical value = 0. Default: 0
    :tf: Frequency transducer time constant (<i>Tf</i>) (&gt;= 0).  Typical value = 0. Default: 0
    :kfcor: Gain of the frequency corrector (<i>Kfcor</i>).  Typical value = 20. Default: 0.0
    :db1: Deadband of the frequency corrector (<i>db1</i>).  Typical value = 0. Default: 0.0
    :wfmax: Upper limit for frequency correction (<i>Wfmax</i>) (&gt; GovSteamEU.wfmin).  Typical value = 0,05. Default: 0.0
    :wfmin: Lower limit for frequency correction (<i>Wfmin</i>) (&lt; GovSteamEU.wfmax).  Typical value = -0,05. Default: 0.0
    :pmax: Maximal active power of the turbine (<i>Pmax</i>).  Typical value = 1. Default: 0.0
    :ten: Electro hydraulic transducer (<i>Ten</i>) (&gt;= 0).  Typical value = 0,1. Default: 0
    :tw: Speed transducer time constant (<i>Tw</i>) (&gt;= 0).  Typical value = 0,02. Default: 0
    :komegacor: Gain of the speed governor (<i>Kwcor</i>).  Typical value = 20. Default: 0.0
    :db2: Deadband of the speed governor (<i>db2</i>).  Typical value = 0,0004. Default: 0.0
    :wwmax: Upper limit for the speed governor (<i>Wwmax</i>) (&gt; GovSteamEU.wwmin).  Typical value = 0,1. Default: 0.0
    :wwmin: Lower limit for the speed governor frequency correction (<i>Wwmin</i>) (&lt; GovSteamEU.wwmax).  Typical value = -1. Default: 0.0
    :wmax1: Emergency speed control lower limit (<i>wmax1</i>).  Typical value = 1,025. Default: 0.0
    :wmax2: Emergency speed control upper limit (<i>wmax2</i>).  Typical value = 1,05. Default: 0.0
    :tvhp: Control valves servo time constant (<i>Tvhp</i>) (&gt;= 0).  Typical value = 0,1. Default: 0
    :cho: Control valves rate opening limit (<i>Cho</i>).  Unit = PU / s.  Typical value = 0,17. Default: 0.0
    :chc: Control valves rate closing limit (<i>Chc</i>).  Unit = PU / s.  Typical value = -3,3. Default: 0.0
    :hhpmax: Maximum control valve position (<i>Hhpmax</i>).  Typical value = 1. Default: 0.0
    :tvip: Intercept valves servo time constant (<i>Tvip</i>) (&gt;= 0).  Typical value = 0,15. Default: 0
    :cio: Intercept valves rate opening limit (<i>Cio</i>).  Typical value = 0,123. Default: 0.0
    :cic: Intercept valves rate closing limit (<i>Cic</i>).  Typical value = -2,2. Default: 0.0
    :simx: Intercept valves transfer limit (<i>Simx</i>).  Typical value = 0,425. Default: 0.0
    :thp: High pressure (HP) time constant of the turbine (<i>Thp</i>) (&gt;= 0).  Typical value = 0,31. Default: 0
    :trh: Reheater  time constant of the turbine (<i>Trh</i>) (&gt;= 0).  Typical value = 8. Default: 0
    :tlp: Low pressure (LP) time constant of the turbine (<i>Tlp</i>) (&gt;= 0).  Typical value = 0,45. Default: 0
    :prhmax: Maximum low pressure limit (<i>Prhmax</i>).  Typical value = 1,4. Default: 0.0
    :khp: Fraction of total turbine output generated by HP part (<i>Khp</i>).  Typical value = 0,277. Default: 0.0
    :klp: Fraction of total turbine output generated by HP part (<i>Klp</i>).  Typical value = 0,723. Default: 0.0
    :tb: Boiler time constant (<i>Tb</i>) (&gt;= 0).  Typical value = 100. Default: 0
    """

    cgmesProfile = TurbineGovernorDynamics.cgmesProfile

    possibleProfileList = {
        "class": [
            cgmesProfile.DY.value,
        ],
        "mwbase": [
            cgmesProfile.DY.value,
        ],
        "tp": [
            cgmesProfile.DY.value,
        ],
        "ke": [
            cgmesProfile.DY.value,
        ],
        "tip": [
            cgmesProfile.DY.value,
        ],
        "tdp": [
            cgmesProfile.DY.value,
        ],
        "tfp": [
            cgmesProfile.DY.value,
        ],
        "tf": [
            cgmesProfile.DY.value,
        ],
        "kfcor": [
            cgmesProfile.DY.value,
        ],
        "db1": [
            cgmesProfile.DY.value,
        ],
        "wfmax": [
            cgmesProfile.DY.value,
        ],
        "wfmin": [
            cgmesProfile.DY.value,
        ],
        "pmax": [
            cgmesProfile.DY.value,
        ],
        "ten": [
            cgmesProfile.DY.value,
        ],
        "tw": [
            cgmesProfile.DY.value,
        ],
        "komegacor": [
            cgmesProfile.DY.value,
        ],
        "db2": [
            cgmesProfile.DY.value,
        ],
        "wwmax": [
            cgmesProfile.DY.value,
        ],
        "wwmin": [
            cgmesProfile.DY.value,
        ],
        "wmax1": [
            cgmesProfile.DY.value,
        ],
        "wmax2": [
            cgmesProfile.DY.value,
        ],
        "tvhp": [
            cgmesProfile.DY.value,
        ],
        "cho": [
            cgmesProfile.DY.value,
        ],
        "chc": [
            cgmesProfile.DY.value,
        ],
        "hhpmax": [
            cgmesProfile.DY.value,
        ],
        "tvip": [
            cgmesProfile.DY.value,
        ],
        "cio": [
            cgmesProfile.DY.value,
        ],
        "cic": [
            cgmesProfile.DY.value,
        ],
        "simx": [
            cgmesProfile.DY.value,
        ],
        "thp": [
            cgmesProfile.DY.value,
        ],
        "trh": [
            cgmesProfile.DY.value,
        ],
        "tlp": [
            cgmesProfile.DY.value,
        ],
        "prhmax": [
            cgmesProfile.DY.value,
        ],
        "khp": [
            cgmesProfile.DY.value,
        ],
        "klp": [
            cgmesProfile.DY.value,
        ],
        "tb": [
            cgmesProfile.DY.value,
        ],
    }

    serializationProfile = {}

    __doc__ += (
        "\n Documentation of parent class TurbineGovernorDynamics: \n"
        + TurbineGovernorDynamics.__doc__
    )

    def __init__(
        self,
        mwbase=0.0,
        tp=0,
        ke=0.0,
        tip=0,
        tdp=0,
        tfp=0,
        tf=0,
        kfcor=0.0,
        db1=0.0,
        wfmax=0.0,
        wfmin=0.0,
        pmax=0.0,
        ten=0,
        tw=0,
        komegacor=0.0,
        db2=0.0,
        wwmax=0.0,
        wwmin=0.0,
        wmax1=0.0,
        wmax2=0.0,
        tvhp=0,
        cho=0.0,
        chc=0.0,
        hhpmax=0.0,
        tvip=0,
        cio=0.0,
        cic=0.0,
        simx=0.0,
        thp=0,
        trh=0,
        tlp=0,
        prhmax=0.0,
        khp=0.0,
        klp=0.0,
        tb=0,
        *args,
        **kw_args,
    ):
        super().__init__(*args, **kw_args)

        self.mwbase = mwbase
        self.tp = tp
        self.ke = ke
        self.tip = tip
        self.tdp = tdp
        self.tfp = tfp
        self.tf = tf
        self.kfcor = kfcor
        self.db1 = db1
        self.wfmax = wfmax
        self.wfmin = wfmin
        self.pmax = pmax
        self.ten = ten
        self.tw = tw
        self.komegacor = komegacor
        self.db2 = db2
        self.wwmax = wwmax
        self.wwmin = wwmin
        self.wmax1 = wmax1
        self.wmax2 = wmax2
        self.tvhp = tvhp
        self.cho = cho
        self.chc = chc
        self.hhpmax = hhpmax
        self.tvip = tvip
        self.cio = cio
        self.cic = cic
        self.simx = simx
        self.thp = thp
        self.trh = trh
        self.tlp = tlp
        self.prhmax = prhmax
        self.khp = khp
        self.klp = klp
        self.tb = tb

    def __str__(self):
        str = "class=GovSteamEU\n"
        attributes = self.__dict__
        for key in attributes.keys():
            str = str + key + "={}\n".format(attributes[key])
        return str
